### ISSUE TITLE
Get targeted people

### ISSUE THREAD

**Issue by BongoKnight** [t4d/StalkPhish#16]
When zip is extracted it's often possible to see a txt file where the activity is logged. For companies automating recuperation of such informations could be great.

**Comment by t4d** [comment]
Hi @BongoKnight. You're right about existing files where are write stolen data, but, I ask myself about that some months ago, and I will not do this. Those data are sensitive data, and I don't want this tool to become a credit card harvester. I hope you understand.
tAd

**Comment by BongoKnight** [comment]
Yes indeed. You've got the point. I've done that in my last company but it
was for protecting impacted client!
