### ISSUE TITLE
ConfParser Error: (<class 'configparser.MissingSectionHeaderError'>, File contains no section headers.

### ISSUE THREAD

**Issue by olugbala** [t4d/StalkPhish#20]
What could be the cause of this and how to solve it?

[root@instance-20190708-2326 stalkphish]# python3 StalkPhish.py -c conf/example.conf

  _____ _        _ _    _____  _     _     _
 / ____| |      | | |  |  __ \| |   (_)   | |
| (___ | |_ __ _| | | _| |__) | |__  _ ___| |__
 \___ \| __/ _` | | |/ /  ___/| '_ \| / __| '_ \
 ____) | || (_| | |   <| |    | | | | \__ \ | | |
|_____/ \__\__,_|_|_|\__\|    |_| |_|_|___/_| |_|

-= StalkPhish - The Phishing Kit stalker - v0.9.8 =-

[!!!] ConfParser Error: (<class 'configparser.MissingSectionHeaderError'>, File contains no section headers.
file: 'conf/example.conf', line: 1
'\ufeff###################################\n', <traceback object at 0x7f2a8926ed48>)
Traceback (most recent call last):
  File "StalkPhish.py", line 355, in ConfAnalysis
    DBfile = CONF.DBfile
AttributeError: 'ConfParser' object has no attribute 'DBfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StalkPhish.py", line 396, in main
    ConfAnalysis(ConfFile)
  File "StalkPhish.py", line 388, in ConfAnalysis
    LOG.error("ConfAnalysis error " + str(err))
NameError: name 'LOG' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StalkPhish.py", line 460, in <module>
    main()
  File "StalkPhish.py", line 453, in main
    LOG.error("Main error " + str(err))
NameError: name 'LOG' is not defined

**Comment by t4d** [comment]
You probably add lines in head of configuration file edited in Windows, try to remove it and try to restart StalkPhish with this 'cleaned' configuration file.

**Comment by t4d** [comment]
Is it ok for you? Can I close this issue?
