### ISSUE TITLE
NameError: name 'LOG' is not defined

### ISSUE THREAD

**Issue by jepunband** [t4d/StalkPhish#27]
hello .. i'm getting this error:

[!!!] ConfParser Error: (<class 'configparser.DuplicateOptionError'>, While reading from 'conf/example.conf' [line 35]: option 'http_proxy' in section 'CONNECT' already exists, <traceback object at 0x7f9dab3fab90>)
Traceback (most recent call last):
  File "StalkPhish.py", line 321, in ConfAnalysis
    DBfile = CONF.DBfile
AttributeError: 'ConfParser' object has no attribute 'DBfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StalkPhish.py", line 358, in main
    ConfAnalysis(ConfFile)
  File "StalkPhish.py", line 351, in ConfAnalysis
    LOG.error("ConfAnalysis error " + str(err))
NameError: name 'LOG' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StalkPhish.py", line 418, in <module>
    main()
  File "StalkPhish.py", line 411, in main
    LOG.error("Main error " + str(err))
NameError: name 'LOG' is not defined

**Comment by jepunband** [comment]
i comment out one of the proxy in conf/example.conf file .. now i get this error:

StalkPhish.py - INFO - Configuration file to use: conf/example.conf
StalkPhish.py - INFO - Database: ./db/StalkPhish.sqlite3
StalkPhish.py - INFO - Main table: StalkPhish
StalkPhish.py - INFO - Investigation table: StalkPhishInvestig
StalkPhish.py - INFO - Files directory: ./files/
StalkPhish.py - INFO - Download directory: ./dl/
StalkPhish.py - INFO - Declared Proxy: socks5://127.0.0.1:9050


StalkPhish.py - ERROR - Proxy connection error, exiting!
StalkPhish.py - ERROR - Main error (<class 'SystemExit'>, SystemExit(10), <traceback object at 0x7fb1c8b12f50

**Comment by t4d** [comment]
In the first error message it seems you have a duplicate _http_proxy_ variable declared. 
For the second error message, it seems you declare a proxy that is not running.
Edit: if you don't need/have any proxy, just comment out the _http_proxy_ line into your config.
