### ISSUE TITLE
Find clonekit of a specific URL

### ISSUE THREAD

**Issue by b00lpy** [t4d/StalkPhish#31]
Hi,

Is it possible to perform a phishing kit scan against a single URL, or a given list from a file, instead of passing through the database?

A kind of:  
`./StalkPhish.py -c conf/example.conf -G http://myurl.example/folder`

**Comment by t4d** [comment]
Hi! You can do it using the -u option, as:
./StalkPhish.py -c conf/example.conf -u 'http://myurl.example/folder'
Then you can do it with a shell script:
for i in $(cat urllist.txt); do /opt/StalkPhish/stalkphish/stalkphish.py -c conf/example.conf -u $i;done
Enjoy!
